oppo={}
oppo['name']='rafi'
oppo['number']=8332085565
oppo['degree']='btech'
oppo['stream']='mechanical'
oppo['marks']='60%'
oppo['interests']='singing'
print(oppo)
nokia={}
nokia['fun']='movies'
oppo.update(nokia)
print(oppo)
print(nokia)
#nokia.clear()
print(nokia)
g=nokia.copy()
print(g)
oppo.pop('fun')
print(oppo)
v=oppo.popitem()
print(oppo)
print(v)
d=oppo.items()
print(d)
s=oppo.keys()
print(s)
b=oppo.values()
print(b)
i=oppo.get('stream')
print(i)
nokia.update(oppo)
print(nokia)
j=(1,5,4,7,8,9,6,4,1,2,3)
kil={}
kill=kil.fromkeys(j)
print(kill)
oppo.setdefault('macha')
print(oppo)
oppo.popitem()
print(oppo)
a=oppo['name']
print(a)
